### ISSUE TITLE
Create config file

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/opm-match#1]
- create a config.do and stick all parameters in there (one hard-coded path per directory)
- create `global basedir /home/ssgprojects/project0002/cdl77/opm-match/`
- rephrase all the others as a function of `$basedir`, i.e., "`global data "$basedir/inputs"` " (more portable)

**Comment by cdlin** [comment]
I made the config file. Do I just include `do config.do` in my other do files?

**Comment by larsvilhuber** [comment]
Yes.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by cdlin** [comment]
done
