### ISSUE TITLE
Create new variables

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/opm-match#2]
Before splitting the files (in 01), create some longitudinal variables, based on the within-file variables
- length of attachment (tenure) to agency
- length of attachment to duty station (posting_length)
- length of occupation (though that *SHOULD* be the same as tenure)
- quarter-on-quarter earnings change (or earnings-level change)

and then match/count duplicates on those as well - separately.

Also, consider also counting exact duplicates if NOT matching on `file_date start_date end_date`

(you might coarsen the change variable, to integer percent values)

**Comment by cdlin** [comment]
The longitudinal variables might only be possible for datasets with pseudo ID. (FOIA2013 and Buzzfeed) I could create them for the other two files with "name",  but many of them are withheld.

Quarter-to-qurater earnings change can be created for datasets with actual pay amount (FOIA2013 and Fedscope) as oppose to interval value.

File_date is effectively year quarter, so dropping it wouldn't effect the match. I'll ignore start date, end date.

**Comment by larsvilhuber** [comment]
2016 also has a person ID - is it not longitudinal?

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by cdlin** [comment]
Yes you're right. I dropped it during the merged and forgot.

**Comment by cdlin** [comment]
done
