### ISSUE TITLE
Create a 02 program for descriptive statistics

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/opm-match#3]
Create a 02 program that describes the proposed match. In particular,
```
duplicates tag $varlist1 , generate(dups1)
tab dups1
```
This will show the extent of the duplicates by ID variable in a simpler fashion

More relevant, I want to have a count of all those that are duplicates, since they *do* count as a *type* of exact match (for this purpose): 
- suppose you have 3x white men, 45, occ=A, etc.
- it doesn't matter who is who - they are the same on all the relevant characteristics.

**Comment by cdlin** [comment]
I believe this is equivalent to what I had under "ambiguous matches". For the count of duplicate, excluding the exact matches

**Comment by larsvilhuber** [comment]
For which you didn't have an automated.

Plus there are more statistics I want to see. So a separate program to tabulate these statistics is useful.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by cdlin** [comment]
Got it.

I think the way duplicate you describes might inflate the matches. 

I.e. 
If FOIA 2013 has 4 obs that are duplicates under the specified varlist, and FOIA 2016 has 5. By only counting the duplicates in the merged matches will give you 20 matches. 
My code right now will say 9 matches instead. I can do both if you want.

**Comment by larsvilhuber** [comment]
Actually,the duplicates command should be run on Datasets prior to the merger.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by cdlin** [comment]
done, follow up in Issue #4
